import { jsPDF } from "jspdf";
import type { AuditResult } from "./psi-analyzer";
import { calculateScores } from "./psi-analyzer";

// Colors
const PRIMARY = [79, 70, 229] as const; // Indigo
const TEXT_DARK = [15, 23, 42] as const;
const TEXT_MUTED = [100, 116, 139] as const;
const GREEN = [34, 197, 94] as const;
const YELLOW = [234, 179, 8] as const;
const RED = [239, 68, 68] as const;

function getScoreColor(score: number, max: number = 10): readonly [number, number, number] {
  const percentage = (score / max) * 100;
  if (percentage >= 70) return GREEN;
  if (percentage >= 40) return YELLOW;
  return RED;
}

function getRatingColor(rating: string): readonly [number, number, number] {
  if (rating === "good") return GREEN;
  if (rating === "needs-improvement") return YELLOW;
  return RED;
}

export function generateAuditPDF(result: AuditResult): jsPDF {
  const doc = new jsPDF();
  const scores = calculateScores(result);
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(...PRIMARY);
  doc.text("MarTech Audit Report", pageWidth / 2, y, { align: "center" });

  y += 10;
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`Generated by Ibero Data | ${new Date().toLocaleDateString()}`, pageWidth / 2, y, {
    align: "center",
  });

  // URL
  y += 15;
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.text("Website Analyzed:", 20, y);
  doc.setTextColor(...PRIMARY);
  doc.text(result.url, 65, y);

  // Scores Section
  y += 20;
  doc.setFontSize(16);
  doc.setTextColor(...TEXT_DARK);
  doc.text("Overall Scores", 20, y);

  y += 10;
  const scoreBoxWidth = 50;
  const scoreBoxHeight = 30;
  const startX = 20;

  // Tracking Score Box
  doc.setFillColor(...getScoreColor(scores.tracking));
  doc.roundedRect(startX, y, scoreBoxWidth, scoreBoxHeight, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(`${scores.tracking}/10`, startX + scoreBoxWidth / 2, y + 15, { align: "center" });
  doc.setFontSize(8);
  doc.text("Tracking Setup", startX + scoreBoxWidth / 2, y + 24, { align: "center" });

  // Privacy Score Box
  doc.setFillColor(...getScoreColor(scores.privacy));
  doc.roundedRect(startX + 60, y, scoreBoxWidth, scoreBoxHeight, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(`${scores.privacy}/10`, startX + 60 + scoreBoxWidth / 2, y + 15, { align: "center" });
  doc.setFontSize(8);
  doc.text("Privacy & Compliance", startX + 60 + scoreBoxWidth / 2, y + 24, { align: "center" });

  // Performance Score Box
  doc.setFillColor(...getScoreColor(scores.performance));
  doc.roundedRect(startX + 120, y, scoreBoxWidth, scoreBoxHeight, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(`${scores.performance}/10`, startX + 120 + scoreBoxWidth / 2, y + 15, { align: "center" });
  doc.setFontSize(8);
  doc.text("Performance", startX + 120 + scoreBoxWidth / 2, y + 24, { align: "center" });

  // Detected Platforms
  y += 45;
  doc.setFontSize(16);
  doc.setTextColor(...TEXT_DARK);
  doc.text("Detected Platforms", 20, y);

  y += 8;
  const detected = result.martech.filter((m) => m.detected);
  const categories = {
    Google: detected.filter((m) => m.category === "google"),
    "Social & Ads": detected.filter((m) => m.category === "social"),
    Consent: detected.filter((m) => m.category === "consent"),
    Analytics: detected.filter((m) => m.category === "analytics"),
  };

  doc.setFontSize(10);
  for (const [category, items] of Object.entries(categories)) {
    if (items.length === 0) continue;

    y += 8;
    doc.setTextColor(...PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text(category, 20, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT_DARK);
    const names = items.map((i) => i.name).join(", ");
    y += 5;
    doc.text(names, 25, y);
  }

  // Not Detected
  const notDetected = result.martech.filter((m) => !m.detected);
  if (notDetected.length > 0) {
    y += 12;
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.text("Not detected: " + notDetected.map((m) => m.name).slice(0, 8).join(", ") + "...", 20, y);
  }

  // Core Web Vitals
  y += 20;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text("Core Web Vitals", 20, y);

  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const metrics = [
    { name: "Largest Contentful Paint (LCP)", value: `${(result.performance.lcp.value / 1000).toFixed(1)}s`, rating: result.performance.lcp.rating },
    { name: "First Contentful Paint (FCP)", value: `${(result.performance.fcp.value / 1000).toFixed(1)}s`, rating: result.performance.fcp.rating },
    { name: "Max Potential FID", value: `${result.performance.fid.value}ms`, rating: result.performance.fid.rating },
    { name: "Cumulative Layout Shift (CLS)", value: `${result.performance.cls.value}`, rating: result.performance.cls.rating },
  ];

  for (const metric of metrics) {
    doc.setTextColor(...TEXT_DARK);
    doc.text(metric.name, 25, y);
    doc.setTextColor(...getRatingColor(metric.rating));
    doc.text(metric.value, 120, y);
    y += 6;
  }

  // Recommendations
  if (result.recommendations.length > 0) {
    y += 10;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...TEXT_DARK);
    doc.text("Recommendations", 20, y);

    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    for (let i = 0; i < Math.min(result.recommendations.length, 5); i++) {
      const rec = result.recommendations[i];
      doc.setTextColor(...PRIMARY);
      doc.text(`${i + 1}.`, 20, y);
      doc.setTextColor(...TEXT_DARK);

      // Word wrap for long recommendations
      const lines = doc.splitTextToSize(rec, 160);
      doc.text(lines, 28, y);
      y += lines.length * 5 + 3;
    }
  }

  // CTA Footer
  y = doc.internal.pageSize.getHeight() - 35;
  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);

  y += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...TEXT_DARK);
  doc.text("Need help implementing these recommendations?", pageWidth / 2, y, { align: "center" });

  y += 7;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);
  doc.text("We specialize in GTM Server-Side, GDPR compliance, and MarTech optimization.", pageWidth / 2, y, { align: "center" });

  y += 7;
  doc.setTextColor(...PRIMARY);
  doc.text("Contact us: info@iberodata.es | https://iberodata.es", pageWidth / 2, y, { align: "center" });

  return doc;
}

export function downloadAuditPDF(result: AuditResult): void {
  const doc = generateAuditPDF(result);
  const filename = `martech-audit-${new URL(result.url).hostname}-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

export function getAuditPDFBase64(result: AuditResult): string {
  const doc = generateAuditPDF(result);
  return doc.output("datauristring");
}
